### ISSUE TITLE
NOT PRINTING HOLA

### ISSUE THREAD

**Issue by Alicia-bites** [Alicia-bites/minishell#33]
# MINISHELL
```
> bonjour | echo hola
$: cat bonjour
hola

```

# EXPECTED
```
amarchan@e1r4p3:~/Documents/test_env$ > bonjour | echo hola
hola
cat bonjour
>
```

It seems like our MInishell put `hola` in file `bonjour`. When it should be that nothing is put in file `bonjour`.

**Comment by BarrierAntho** [comment]
# STATUS:
Fixed

# COMMIT:
8fdbf264ae7c067b72fed0f8b8778148a79915f5

# MINISHELL:
```
$: cd smb_test/
$: rm bonjour
$: > bonjour | echo hola
hola
$: cat bonjour
$: 
```
