### ISSUE TITLE
FILE SHOULD NOT BE FOUND

### ISSUE THREAD

**Issue by Alicia-bites** [Alicia-bites/minishell#40]
# MINISHELL
```$: echo hola > srcs/bonjour
$: echo hey > srcs/hello
$: >srcs/bonjour >srcs/hello <prout```

#EXPECTED
after all this commands, should say `prout:no such file or directory`

# TOKENIZATION
```
index = 0
token = >
toktype = 11
-----------------------------------------
index = 1
token = srcs/bonjour
toktype = 15
-----------------------------------------
index = 2
token = >
toktype = 11
-----------------------------------------
index = 3
token = srcs/hello
toktype = 15
-----------------------------------------
index = 4
token = <
toktype = 10
-----------------------------------------
index = 5
token = prout
toktype = 15
-----------------------------------------
```

**Comment by BarrierAntho** [comment]
STATUS:
Message and behavior ok but exit status wrong
